import * as stylex from '@stylexjs/stylex';
import { tokens } from './tokens.stylex';
export const controls = stylex.create({
  button: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: tokens.space8,
    minHeight: 44,
    minWidth: 44,
    paddingBlock: tokens.space8,
    paddingInline: tokens.space16,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: tokens.border,
    borderRadius: tokens.radiusMd,
    backgroundColor: {
      default: tokens.surface,
      ':hover': tokens.surfaceMuted,
      ':active': tokens.surfaceMuted,
      ':disabled': tokens.surface,
    },
    color: tokens.textPrimary,
    fontSize: 14,
    fontWeight: 600,
    lineHeight: 1.5,
    opacity: { default: 1, ':disabled': 0.55 },
    transitionProperty: 'background-color, border-color, color, transform',
    transitionDuration: {
      default: tokens.durationFast,
      '@media (prefers-reduced-motion: reduce)': '0s',
    },
    textDecoration: 'none',
    position: 'relative',
    cursor: { default: 'pointer', ':disabled': 'not-allowed' },
    outlineColor: tokens.focus,
    transform: {
      default: 'translateY(0)',
      ':active': 'translateY(1px)',
      ':disabled': 'none',
    },
  },
  primary: {
    backgroundColor: {
      default: tokens.action,
      ':hover': tokens.actionHover,
      ':active': tokens.actionPressed,
      ':disabled': tokens.action,
    },
    borderColor: tokens.action,
    color: tokens.onAction,
  },
  ghost: {
    backgroundColor: {
      default: 'transparent',
      ':hover': tokens.surfaceMuted,
      ':active': tokens.surfaceMuted,
      ':disabled': 'transparent',
    },
    borderColor: 'transparent',
  },
  danger: {
    backgroundColor: {
      default: tokens.danger,
      ':hover': tokens.dangerHover,
      ':active': tokens.dangerHover,
      ':disabled': tokens.danger,
    },
    borderColor: tokens.danger,
    color: tokens.onAction,
  },
  small: { paddingInline: tokens.space12, fontSize: 13 },
  invalid: { borderColor: { default: tokens.danger, ':hover': tokens.danger } },
  active: {
    backgroundColor: tokens.actionTint,
    borderColor: tokens.action,
    color: tokens.action,
    textDecoration: 'underline',
    textUnderlineOffset: 4,
  },
  field: { display: 'grid', gap: tokens.space8, minWidth: 0, fontSize: 14 },
  input: {
    width: '100%',
    minWidth: 0,
    minHeight: 44,
    paddingBlock: tokens.space8,
    paddingInline: tokens.space12,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: {
      default: tokens.controlBorder,
      ':hover': tokens.action,
      ':disabled': tokens.controlBorder,
    },
    borderRadius: tokens.radiusMd,
    backgroundColor: tokens.surface,
    color: tokens.textPrimary,
    fontSize: 14,
    fontWeight: 400,
    lineHeight: 1.5,
    outlineColor: tokens.focus,
    opacity: { default: 1, ':disabled': 0.55 },
    cursor: { default: 'auto', ':disabled': 'not-allowed' },
  },
  stack: { display: 'grid', gap: 20, minWidth: 0 },
  row: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: tokens.space8,
    alignItems: 'center',
  },
  muted: {
    color: tokens.textSecondary,
    fontSize: 13,
    lineHeight: 1.7,
    margin: 0,
  },
  heading: { fontSize: 18, fontWeight: 600, margin: 0 },
  card: {
    padding: tokens.space24,
    minWidth: 0,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: tokens.border,
    backgroundColor: tokens.surface,
    borderRadius: tokens.radiusLg,
    boxShadow: tokens.shadowNone,
  },
});
