import * as stylex from '@stylexjs/stylex';
import { tokens } from './tokens.stylex';
export const controls = stylex.create({
  button: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 44,
    minWidth: 44,
    paddingBlock: 9,
    paddingInline: 14,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: tokens.line,
    borderRadius: 8,
    backgroundColor: { default: tokens.surface, ':hover': tokens.soft },
    color: tokens.ink,
    fontSize: 14,
    textDecoration: 'none',
    position: 'relative',
    cursor: { default: 'pointer', ':disabled': 'not-allowed' },
    outlineColor: tokens.focus,
    transform: {
      default: 'translateY(0)',
      ':active': 'translateY(1px)',
      ':disabled': 'none',
    },
  },
  primary: {
    backgroundColor: { default: tokens.accent, ':hover': tokens.accentHover },
    borderColor: tokens.accent,
    color: 'white',
  },
  ghost: {
    backgroundColor: { default: 'transparent', ':hover': tokens.soft },
    borderColor: 'transparent',
  },
  danger: {
    backgroundColor: { default: tokens.danger, ':hover': tokens.dangerHover },
    borderColor: tokens.danger,
    color: 'white',
  },
  small: { paddingInline: 10, fontSize: 13 },
  invalid: { borderColor: tokens.danger },
  active: {
    backgroundColor: tokens.soft,
    borderColor: tokens.accent,
    color: tokens.accent,
  },
  field: { display: 'grid', gap: 8, minWidth: 0, fontSize: 14 },
  input: {
    width: '100%',
    minWidth: 0,
    minHeight: 44,
    padding: 10,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: tokens.line,
    borderRadius: 6,
    backgroundColor: tokens.surface,
    color: tokens.ink,
    outlineColor: tokens.focus,
    opacity: { default: 1, ':disabled': 0.5 },
    cursor: { default: 'auto', ':disabled': 'not-allowed' },
  },
  stack: { display: 'grid', gap: 20, minWidth: 0 },
  row: { display: 'flex', flexWrap: 'wrap', gap: 10, alignItems: 'center' },
  muted: { color: tokens.muted, fontSize: 13, lineHeight: 1.7, margin: 0 },
  heading: { fontSize: 18, fontWeight: 650, margin: 0 },
  card: {
    padding: 24,
    minWidth: 0,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: tokens.line,
    backgroundColor: tokens.surface,
    borderRadius: 10,
  },
});
