import * as stylex from '@stylexjs/stylex';
import { tokens } from './tokens.stylex';

export const siteStyles = stylex.create({
  body: {
    color: tokens.textPrimary,
    backgroundColor: tokens.page,
    fontSize: 16,
  },
  frame: { minHeight: '100dvh', display: 'flex', flexDirection: 'column' },
  width: {
    width: '100%',
    maxWidth: 1200,
    paddingInline: { default: 40, '@media (max-width: 600px)': 16 },
    marginInline: 'auto',
  },
  nav: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: tokens.space8,
    minHeight: { default: 72, '@media (max-width: 600px)': 64 },
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.border,
  },
  brand: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: tokens.space8,
    minHeight: 44,
    flexShrink: 0,
    color: tokens.textPrimary,
    fontSize: { default: 22, '@media (max-width: 600px)': 18 },
    fontWeight: 700,
    textDecoration: 'none',
    letterSpacing: '-0.04em',
  },
  mark: {
    width: { default: 32, '@media (max-width: 600px)': 28 },
    height: { default: 32, '@media (max-width: 600px)': 28 },
  },
  navLinks: {
    display: 'flex',
    alignItems: 'center',
    gap: { default: 24, '@media (max-width: 600px)': 8 },
  },
  navLink: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: 44,
    minWidth: 44,
    fontSize: 14,
    fontWeight: 500,
    textDecoration: { default: 'none', ':hover': 'underline' },
    color: {
      default: tokens.textPrimary,
      ':hover': tokens.action,
      ':active': tokens.actionPressed,
    },
    textUnderlineOffset: 5,
  },
  githubLink: { gap: tokens.space8, justifyContent: 'center' },
  githubLabel: {
    display: { default: 'inline', '@media (max-width: 600px)': 'none' },
  },
  link: {
    color: {
      default: tokens.action,
      ':hover': tokens.actionHover,
      ':active': tokens.actionPressed,
    },
    minHeight: 44,
    display: 'inline-flex',
    alignItems: 'center',
    gap: tokens.space8,
    textUnderlineOffset: 5,
  },
  homeMain: { flex: 1 },
  hero: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(0, 1.2fr) minmax(0, 1fr)',
      '@media (max-width: 760px)': 'minmax(0, 1fr)',
    },
    alignItems: 'center',
    columnGap: tokens.space24,
    rowGap: tokens.space24,
    paddingBlock: {
      default: '72px 64px',
      '@media (max-width: 760px)': '40px 32px',
    },
  },
  eyebrow: {
    margin: 0,
    color: tokens.textSecondary,
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: '0.08em',
  },
  heroTitle: {
    fontSize: {
      default: 52,
      '@media (max-width: 1100px)': 44,
      '@media (max-width: 760px)': 36,
      '@media (max-width: 400px)': 32,
    },
    fontWeight: 700,
    lineHeight: 1.2,
    letterSpacing: '-0.04em',
    textWrap: 'balance',
    marginBlock: tokens.space24,
  },
  heroAccent: { display: 'block', color: tokens.action },
  heroIntro: {
    fontSize: { default: 17, '@media (max-width: 760px)': 15 },
    lineHeight: 1.8,
    maxWidth: 500,
    color: tokens.textSecondary,
    marginBlock: '0 24px',
  },
  heroStatus: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.space8,
    fontSize: 13,
    color: tokens.textSecondary,
    margin: 0,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    backgroundColor: tokens.sage,
    flexShrink: 0,
  },
  explore: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: tokens.space16,
    minHeight: 44,
    paddingInline: tokens.space16,
    borderRadius: tokens.radiusMd,
    fontWeight: 600,
    fontSize: 14,
    textDecoration: 'none',
    color: tokens.onAction,
    backgroundColor: {
      default: tokens.action,
      ':hover': tokens.actionHover,
      ':active': tokens.actionPressed,
    },
  },
  artwork: {
    width: '100%',
    height: { default: 380, '@media (max-width: 760px)': 150 },
    objectFit: 'contain',
  },
  section: {
    paddingBottom: { default: 80, '@media (max-width: 760px)': 40 },
    scrollMarginTop: tokens.space24,
  },
  sectionHeading: {
    fontSize: { default: 24, '@media (max-width: 600px)': 20 },
    fontWeight: 600,
    marginBlock: '0 24px',
    letterSpacing: '-0.02em',
  },
  empty: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.space32,
    backgroundColor: tokens.surfaceMuted,
    borderRadius: tokens.radiusLg,
    padding: { default: 40, '@media (max-width: 600px)': 24 },
  },
  emptyArt: {
    flexShrink: 0,
    display: { default: 'block', '@media (max-width: 600px)': 'none' },
  },
  emptyTitle: {
    marginBlock: '0 12px',
    fontSize: { default: 22, '@media (max-width: 600px)': 20 },
    fontWeight: 600,
    letterSpacing: '-0.02em',
  },
  description: {
    color: tokens.textPrimary,
    maxWidth: 620,
    lineHeight: 1.8,
    fontSize: 14,
    margin: 0,
  },
  development: { marginTop: tokens.space12, fontSize: 13, fontWeight: 500 },
  cards: {
    display: 'grid',
    gap: tokens.space24,
    gridTemplateColumns: {
      default: 'repeat(3, minmax(0, 1fr))',
      '@media (max-width: 1000px)': 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 600px)': 'minmax(0, 1fr)',
    },
    padding: 0,
    margin: 0,
    listStyle: 'none',
  },
  card: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    padding: tokens.space24,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: {
      default: tokens.border,
      ':hover': tokens.controlBorder,
      ':active': tokens.action,
    },
    backgroundColor: { default: tokens.surface, ':hover': tokens.page },
    borderRadius: tokens.radiusLg,
    textDecoration: 'none',
    overflowWrap: 'anywhere',
  },
  cardTop: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    color: tokens.action,
  },
  cardIcon: {
    borderRadius: tokens.radiusMd,
    backgroundColor: tokens.actionTint,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 600,
    marginBlock: '16px 8px',
    color: tokens.textPrimary,
  },
  cardDescription: {
    fontSize: 14,
    lineHeight: 1.7,
    marginBlock: '0 24px',
    color: tokens.textSecondary,
  },
  category: { marginTop: 'auto', fontSize: 12, color: tokens.textSecondary },
  footer: {
    paddingBlock: '32px 24px',
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: tokens.border,
  },
  footerTop: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: tokens.space24,
    flexDirection: { default: 'row', '@media (max-width: 760px)': 'column' },
  },
  footerIntro: {
    fontSize: 14,
    color: tokens.textSecondary,
    marginBlock: '12px 4px',
  },
  ecosystem: { fontSize: 13, color: tokens.textSecondary, margin: 0 },
  footerLinks: {
    display: 'flex',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    columnGap: tokens.space24,
  },
  footerBottom: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: tokens.space8,
    flexDirection: { default: 'row', '@media (max-width: 760px)': 'column' },
    marginTop: tokens.space32,
    fontSize: 12,
    color: tokens.textSecondary,
  },
  // Shared 404 typography; the homepage has its own two-column hero.
  main: {
    flex: 1,
    paddingBlock: { default: 72, '@media (max-width: 600px)': 40 },
  },
  badge: {
    display: 'inline-block',
    fontSize: 12,
    letterSpacing: '0.06em',
    color: tokens.action,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: tokens.border,
    borderRadius: tokens.radiusSm,
    paddingBlock: 6,
    paddingInline: 10,
  },
  title: {
    maxWidth: 750,
    textWrap: 'balance',
    fontSize: { default: 56, '@media (max-width: 600px)': 36 },
    fontWeight: 700,
    lineHeight: 1.2,
    letterSpacing: '-0.045em',
    marginBlock: 24,
  },
  intro: {
    fontSize: 18,
    color: tokens.textSecondary,
    maxWidth: 680,
    lineHeight: 1.8,
  },
  skip: {
    position: 'absolute',
    top: 8,
    left: 8,
    padding: 12,
    backgroundColor: tokens.surface,
    zIndex: 100,
    transform: { default: 'translateY(-150%)', ':focus': 'translateY(0)' },
  },
});
