import * as stylex from '@stylexjs/stylex';
import { tokens } from './tokens.stylex';

export const siteStyles = stylex.create({
  frame: { minHeight: '100dvh', display: 'flex', flexDirection: 'column' },
  nav: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    paddingBlock: 20,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.line,
  },
  width: {
    width: '100%',
    maxWidth: 1080,
    paddingInline: { default: 40, '@media (max-width: 600px)': 20 },
    marginInline: 'auto',
  },
  brand: {
    color: tokens.ink,
    fontSize: 20,
    fontWeight: 750,
    textDecoration: 'none',
    letterSpacing: '-0.04em',
  },
  link: {
    color: tokens.accent,
    minHeight: 44,
    display: 'inline-flex',
    alignItems: 'center',
    textUnderlineOffset: 5,
  },
  main: {
    flex: 1,
    paddingBlock: { default: 72, '@media (max-width: 600px)': 40 },
  },
  badge: {
    display: 'inline-block',
    fontSize: 12,
    letterSpacing: '0.06em',
    color: tokens.accent,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: tokens.line,
    borderRadius: 6,
    paddingBlock: 6,
    paddingInline: 10,
  },
  title: {
    maxWidth: 750,
    textWrap: 'balance',
    fontSize: { default: 56, '@media (max-width: 600px)': 36 },
    fontWeight: 650,
    lineHeight: 1.2,
    letterSpacing: '-0.045em',
    marginBlock: 24,
  },
  intro: { fontSize: 18, color: tokens.muted, maxWidth: 680, lineHeight: 1.8 },
  section: { marginTop: 64 },
  sectionHeading: { fontSize: 15, fontWeight: 600, marginBottom: 16 },
  empty: {
    backgroundColor: tokens.soft,
    borderRadius: 12,
    padding: { default: 32, '@media (max-width: 600px)': 24 },
  },
  emptyTitle: { marginBlock: '0 12px', fontSize: 24, fontWeight: 600 },
  description: {
    color: tokens.muted,
    maxWidth: 650,
    lineHeight: 1.8,
    margin: 0,
  },
  footer: {
    paddingBlock: 24,
    fontSize: 13,
    color: tokens.muted,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: tokens.line,
  },
  cards: {
    display: 'grid',
    gap: 16,
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 260px), 1fr))',
    padding: 0,
    listStyle: 'none',
  },
  card: {
    display: 'block',
    padding: 24,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: tokens.line,
    borderRadius: 12,
    textDecoration: 'none',
  },
  skip: {
    position: 'absolute',
    top: 8,
    left: 8,
    padding: 12,
    backgroundColor: tokens.surface,
    zIndex: 100,
    transform: { default: 'translateY(-150%)', ':focus': 'translateY(0)' },
  },
});
