import * as stylex from '@stylexjs/stylex';
import { tokens as t } from '../../styles/tokens.stylex';
export const converterStyles = stylex.create({
  layout: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(0, 1fr) 320px',
      '@media (max-width: 900px)': 'minmax(0, 1fr)',
    },
    gap: t.space24,
    alignItems: 'start',
  },
  file: { gridColumn: '1 / -1', minWidth: 0, display: 'grid', gap: t.space12 },
  settings: {
    gridColumn: { default: '2', '@media (max-width: 900px)': 'auto' },
    gridRow: { default: '2 / span 2', '@media (max-width: 900px)': 'auto' },
    display: 'grid',
    gap: t.space16,
    minWidth: 0,
    padding: t.space16,
    backgroundColor: t.surface,
    borderRadius: t.radiusLg,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: t.border,
  },
  preview: {
    gridColumn: { default: '1', '@media (max-width: 900px)': 'auto' },
    gridRow: { default: '2', '@media (max-width: 900px)': 'auto' },
    minWidth: 0,
  },
  result: {
    gridColumn: { default: '1', '@media (max-width: 900px)': 'auto' },
    gridRow: { default: '3', '@media (max-width: 900px)': 'auto' },
    display: 'grid',
    gap: t.space12,
    minWidth: 0,
    scrollMarginTop: t.space24,
  },
  heading: { fontSize: 18, fontWeight: 600, margin: '0 0 12px' },
  note: {
    fontSize: 13,
    lineHeight: 1.7,
    color: t.textSecondary,
    margin: 0,
    overflowWrap: 'anywhere',
  },
  error: {
    fontSize: 14,
    lineHeight: 1.6,
    color: t.danger,
    margin: 0,
    overflowWrap: 'anywhere',
  },
  strip: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: t.space12,
    minWidth: 0,
    flexWrap: 'wrap',
  },
  fileName: {
    display: 'block',
    maxWidth: '100%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  metadata: { minWidth: 0, flex: '1 1 180px' },
  row: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: t.space8,
  },
  group: { borderWidth: 0, padding: 0, margin: 0, minWidth: 0 },
  legend: { fontWeight: 600, marginBottom: t.space8 },
  choices: { display: 'flex', gap: t.space8, flexWrap: 'wrap' },
  choice: {
    display: 'flex',
    alignItems: 'center',
    gap: t.space8,
    minHeight: 44,
    padding: '8px 12px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: t.controlBorder,
    borderRadius: t.radiusMd,
    cursor: 'pointer',
    backgroundColor: { default: t.surface, ':hover': t.page },
    fontWeight: 500,
    flexGrow: 1,
  },
  chosen: {
    backgroundColor: { default: t.actionTint, ':hover': t.actionTint },
    borderColor: t.action,
    textDecoration: 'underline',
    textUnderlineOffset: 4,
  },
  disabled: { opacity: 0.55, cursor: 'not-allowed' },
  radio: {
    accentColor: t.action,
    width: 18,
    height: 18,
    margin: 0,
    flexShrink: 0,
  },
  previews: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(2,minmax(0,1fr))',
      '@media (max-width: 900px)': 'minmax(0,1fr)',
    },
    gap: t.space12,
  },
  figure: { margin: 0, minWidth: 0 },
  mobileHidden: {
    display: { default: 'block', '@media (max-width: 900px)': 'none' },
  },
  imageBox: {
    display: 'grid',
    placeItems: 'center',
    height: { default: 300, '@media (max-width: 900px)': 260 },
    padding: t.space8,
    borderRadius: t.radiusMd,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: t.border,
    backgroundColor: t.surface,
    backgroundImage: `repeating-conic-gradient(${t.surfaceMuted} 0% 25%, transparent 0% 50%)`,
    backgroundSize: '16px 16px',
  },
  image: {
    display: 'block',
    width: '100%',
    height: '100%',
    maxHeight: { default: 282, '@media (max-width: 900px)': 242 },
    objectFit: 'contain',
  },
  caption: {
    fontSize: 13,
    marginBlock: t.space8,
    lineHeight: 1.6,
    overflowWrap: 'anywhere',
  },
  choiceHint: { display: 'block', fontSize: 12, fontWeight: 400 },
  mobileTabs: {
    display: { default: 'none', '@media (max-width: 900px)': 'flex' },
    gap: t.space8,
    marginBottom: t.space12,
  },
  swatch: (color: string) => ({
    display: 'inline-block',
    width: 28,
    height: 28,
    backgroundColor: color,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: t.controlBorder,
    borderRadius: t.radiusSm,
  }),
  details: {
    gridColumn: '1 / -1',
    maxWidth: '100%',
    overflowWrap: 'anywhere',
    fontSize: 12,
  },
});
